### ISSUE TITLE
Add support for background seismicity in Hazard calculations

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#102]
AS SRM team

We want opensha hazard calcluator to support NZ background seismicity

so we have curves with or without this data

**Comment by chrisbc** [comment]
@voj I'll start a thread here so we're all in the loop. re Hazard curves including NZ background seismicity....

@mcg-gns : "it would be helpful if we can add the gridded seis rates, from within the polygon and are > Fault Mmin to the MFD curve plot. These are the rates that get removed. let me know if that doesn't make sense!"

In our inversion setup (in NSHM_InversionTargetMFDs class) we subtract the background seismicity falling within fault polygons from the overall MFD target, so that the inversion does not try to fit MFD curves using smaller ruptures that would already be in our BG seismicity. As a result the rupture rates produced by the inversion will exclude that portion of BG seismicity that is occurring 'on fault' (really it's 'near fault' ).  And this is why we need to add this into the hazard calculation.

**Comment by chrisbc** [comment]
@voj we should get back onto this pretty soon!

**Comment by voj** [comment]
done
