### ISSUE TITLE
Validation: Clarify relationships between the Rupture Set objects

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#11]
As **NZ Opensha users**

**We want** to be sure we understand how these objects are related

 - **FaultModel** components:
     - **FaultSection** - the `<i{N}` XML elements
     - **FaultTrace**
     - **FaultTrace Point** (lat lon, in [opensha convention)](https://opensha.org/Glossary.html#strike-dip--rake-focal-mechanism)
     - **SubSection**  - from the  `getSubSectionsList()` method
     - **StirlingGriddedSurface**
 - **DeformationModel** components (ie the container for deformation attributes like **avg slip-rate, avg rake** etc

**So that** we can avoid confusion in our opensha travels 

Noting that the FaultModel above is the surface-fault model derived from the XML, NOT the pre-subsectioned model derived from our Hikurangi data. @thingbaijam  - will we have a deformation model for this too? - We would be having a one (or more?) - it'd be interesting to workout the data format. 

**Done criteria**

 - [ ] create test data and tests to examine the elements in question
 - [ ] create some simple visualisations to support the test findings.
 - [ ] write up a summary of these findings (pref in markdown) for the /doc folder in this repo  (based on @thingbaijam doc)

**Comment by chrisbc** [comment]
discussion notes:

- sample of NZ CFM XML in /data folder
- /tests

**Comment by ornearius** [comment]
This depends on opensha-commons to be checked out for the gradle.build

**Comment by chrisbc** [comment]
> This depends on opensha-commons to be checked out for the gradle.build
> Need to check out where opensha-ucerf3 artifacts are

@ornearius  I think if you follow https://github.com/GNS-Science/nshm-nz-opensha/blob/master/README.md it covers the dependencies. Hopefully it's up to date!

**Comment by chrisbc** [comment]
One possible trap - Kevin's made recent commits to opensha-*:master. So theres a chance some of our tests are now failing.
