### ISSUE TITLE
Integrate Fault Models as project resources

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#118]
Using same pattern as UCERF3 (FM_3.2 etc)  with enum + Data Loader

So that that users can be certain they have the  data used in NZSHM22 in the future.

Done when we've converted:
 - [ ] CFM V0.3 (sans TVZ)
 - [ ] CFM V0.9 
 - [ ] CFM V0.9 (sans TVZ)
 - [ ] Hikurangi 10Km
 - [ ] Hikirangi 30km
 - [ ] HikurangiKermadec 10km
 - [ ] HikurangiKermadec 30km
 - [ ] add method to rupture builder so clients can set desired model via enum (in addition to current approach)

**Comment by voj** [comment]
done
