### ISSUE TITLE
Validation: in OpenSHA XML, does <iN element ID matter? 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#12]
In the XML input data (see example below)

 - must the element id / sectionID agree?
 - must **elementID** always start at 0
 - must **sectionID** always start at 0
```
<?xml version="1.0" encoding="utf-8"?>
 <OpenSHA>
  <FaultModel>
   <i0 aseismicSlipFactor="0.0" aveDip="75.0" aveLongTermSlipRate="0.6" aveLowerDepth="20.0" 
     aveRake="330.0" aveUpperDepth="0.0" connector="false" couplingCoeff="1.0" dipDirection="300.8" parentSectionId="-1"
     sectionId="0" sectionName="Akatarawa" slipRateStDev="0.3">

```

**Comment by voj** [comment]
Looking at the code starting at `scratch.UCERF3.utils.FaultSystemIO.fsDataFromXML(Element)` :

- Element ids have to start at `i0` and there must not be any gaps in the count. They do not need to be in order. This is only used for iterating over the elements. The count is not used for anything else.
- This means that the `sectionId` is not related to the `elementId`.

Simply from looking at the import, I cannot tell if there are requirements on `sectionID` values later on.

**Comment by thingbaijam** [comment]
> Looking at the code starting at `scratch.UCERF3.utils.FaultSystemIO.fsDataFromXML(Element)` :
> 
> * Element ids have to start at `i0` and there must not be any gaps in the count. They do not need to be in order. This is only used for iterating over the elements. The count is not used for anything else.
> * This means that the `sectionId` is not related to the `elementId`.
> 
> Simply from looking at the import, I cannot tell if there are requirements on `sectionID` values later on.

Thanks; sectionID and elementID not related to each other do make sense - as otherwise, it would make either one (of them) redundant.
