### ISSUE TITLE
automated rupture file naming conventions

### ISSUE THREAD

**Issue by voj** [GNS-Science/nshm-nz-opensha#123]
From slack:
While we're looking at rupture building I want to standardise how we name output files. We're vacillatting about adding meta data to filenames. but I think we should do it. And I'd like a convention so the parms are traceable to the setter method names.
e.g.
```
setMaxTotalAzimuthChange(50.0d) >> ..._mxTtlAzmChn(50.0)...
```

which is rule-based....

1.  drop set/get
2.  Always take first letter (vowel or consonant)
3.  now take up to two more consonants
4.  chuck () around the value
5.  for order, let's just alphabetise them
6.  Although maybe not on that last one. I can see a case for the FaultModel coming first for example, hmmmm

OK ,may just 1 consonant will work
```
setMaxTotalAzimuthChange(50.0d) >> ...mxTtAzCh(50.0)...
```

We'll need to experiment

**Comment by chrisbc** [comment]
closed by #123 and #134
