### ISSUE TITLE
Gridded hazard calc feature

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#143]
**We want** a gridded hazard calculation 

**So that** we're able to create map visualisations of hazard outputs (e.g heat maps)

 - set the grid size  - default is 10km, but this 
 - set the the region from defined enums  (eg NZTEST / CSEP)
 - set the region as a polygon shape (optional)
 - forecast_time can be set (in years) defaults to 50 (years)
 - a list of Probability of exceedance thresholds is passed in (eg 2%, 10%)  the chance that a event occurs on the horizon
 - returns a table of values, one per grid location/PofET.

**Comment by voj** [comment]
> set the grid size - default is 10km, but this

Is it OK if the grid spacing is specified in degrees? That's what `GriddedRegion` already supports. Otherwise I'll assume 111km per degree at the equator for longitude and for latitude anywhere, and work it out from there.

**Comment by voj** [comment]
done
