### ISSUE TITLE
Add named fault support for FaultModels

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#147]
**We want** named faults defined

**so that** reporting features and scecVDO can use aggregated faults composed of multiple FaultSections

**Done When**

 - Use the alt names file as used in UCERF3....FaultModels data folder
    _sorry I looked but couldn't find it -  but it's there somewhere_
 - setup one named fault **Wellington Hutt Valley** comprising all the numbered sections of WHV (approx 5 sections)
 - modify the class **NZSHM22_FilteredInversionDiagnosticsReport** to accept a filter predicate filter  functino and define a function that uses named sections. 
 -  update / add tests

**Comment by voj** [comment]
@chrisbc the description of this issue specifically says we want this to work in scecVDO, but the "Done When" section ignores this. I'm going to work towards the gals in the "Done When" section.

**Comment by voj** [comment]
@chrisbc my understanding is that it will not! This information is not written into the solution as far as I can tell. We'll see what happens :-)
