### ISSUE TITLE
Fix package namespaces

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#15]
Background: We kept **scratch/kevin/etc** for package names but that was a dumb idea -  as it confuses this code with those in the opensha-* world. 

So, let'sagree some new namespaces and reorg our work to make more sense.

Please Propose/agree new names here,  then someone can pick it up.

**Comment by ornearius** [comment]
If this is GNS code then the correct namespace for Java is nz.cri.gns.<project> as that is our domain name.
This avoids external conflicts.

**Comment by voj** [comment]
I agree. And we should be careful not to have classes directly in the `nz.cri.gns` package to avoid conflicts with other GNS packages. It's probably best to mirror Kevin's package structure as far as possible to make it easier to comprehend what's going on. For example, if we write a NZ specific class that could have gone into `scratch.UCERF3.utils`, we should put it in `nz.cri.gns.UCERF3.utils`

**Comment by voj** [comment]
The [gradle docs](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html) recommend a different folder structure from what we currently have. For example, Java production code should go into `src/main/java` and tests should go in `src/test/java`. I recommend we follow conventions to make it easier to use build and test tools. This will probably also help with @chrisbc 's problem of accessing resource files.

**Comment by chrisbc** [comment]
Some thoughts on this....

> For example, if we write a NZ specific class that could have gone into `scratch.UCERF3.utils`, we should put it in `nz.cri.gns.UCERF3.utils`

@voj - I suggest that for NZ specific changes we won't add this to the main opensha-* repos (where that namespace 'lives'). 

If we do need to change some generic  code then our changes should made in a fork of the relevant opensha-* repo. And it should retain the original namespaces so it can be easily merged back into the upstream USGS project(s) at that teams discretion. 

For code that is NSHM NZ specific, let's consider a root NS like **nz.cri.gns.NSHM**. This will disambiguate nicely and should cover all our work in the **nshm-ns-opensha** repo. 

We're FOSS, so USGS or anyone can take NZ features and fold them upstream into the generic / core projects if that seems useful.

**Comment by chrisbc** [comment]
Update - I discussed this with @kevinmilner today. He's happy with this, and he also reminded me that there'll continue to be changes in the upstream opensha-* repos as lots will be happening there for UCERF4 etc.

**Comment by chrisbc** [comment]
And we have Core team approval to use **nz.cri.gns.NSHM** as our root namespace!

 So now let's agree how to manage co-ordinate this change internally.

**Comment by voj** [comment]
@chrisbc if we follow the standard directory structure it should be 

```
├── build.gradle
├── settings.gradle
└── src
    ├── main
    │   └── java
    │       └── nz
    │           └── cri
    │               └── ...
    └── test
        ├── java    
        │   └── nz
        │       └── cri
        │           └── ...
        └── resources
            └── FaultModels
```

it's not quite what's in your branch. What do you reckon? Changing it to the standard might save us a few headaches later.

**Comment by voj** [comment]
And the python code could then go into `src/main/python` and `src/test/python`

**Comment by chrisbc** [comment]
Yes - I think we should standardise it as you suggest. I'll make those changes in my branch and let you know - thanks!

**Comment by chrisbc** [comment]
@voj I can't get this to work with `\test` nested inside `\src` and most places seem to have src and test as siblings anyway.

Are you happy with this?... I finally have this working in both eclipse (aaargh) and gradle (ahh)

```
├── build.gradle
├── settings.gradle
├── src
│   └── main
│      └── java
│           └── nz
│               └── cri
│                   └── 
└── test
    ├── java    
    │   └── nz
    │       └── cri
    │           └── ...
    └── resources
        └──
```
