### ISSUE TITLE
Configure system pre-reqs on beavan cluster

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#16]
**The team** want to run the inversion on **the beaven cluster**,

**So that** we can test scaling and get some preliminary results on a low-cost MPI cluster

 but we're going to need newer software installed there. We need

  - [x] java 8 (1.8) JRE on all worker nodes
  - [x] ~latest python3 on all nodes~ SKIPPED since 3.6 is available already.
  - [x] java 8 (1.8) JDK (on master) so we can compile in situ~

**NB** if  anyone else is ever confused by this,  **java  8 == java 1.8** see https://stackoverflow.com/questions/53642402/why-do-i-see-open-jdk-1-8-instead-of-java-8

**NB** on beavan the java JDKs have been installed to /opt/sw/java both 8 and 11 are now available.

**Comment by ornearius** [comment]
Should not need the JDK. If we set up the build to produce runnable artifacts we can just load and run them.
I would suggest using Java 11 as 8 is getting a bit long in the tooth.
It might also be worth looking at building standalone apps that target the cluster architecture. This would mean that we would not require any changes to the servers.

**Comment by chrisbc** [comment]
Thanks @ornearius  - agree  Java 11 (since 12 not supported) 
 - scratch the JDK as this will be catered for by the gradle updates (you'll raise a ticket on this)

**Comment by chrisbc** [comment]
@ornearius I just spoke to Roger Williams and this is the approach we can take....

 - [ ] install the java 8 JRE binaries into the /opt/sw/java folder (I'm currently owner of this folder) this path is mapped on all cluster nodes
 - [X] we can access python 3 in /op/sw also (latest is 3.6) 

Also FYI - as our data files will be large we'll use the /shared folder to read/write our datasets. This storage is not backed up but has plenty of spare capacity.

**Comment by chrisbc** [comment]
TODO:

 - [ ] create scripts folder in project for the cluster-specific (PBS) scripts
 - [ ] add a readme for this stuff
