### ISSUE TITLE
BUG: Inversions on stirling ruptsets fail

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#160]
Something odd in the fault polygon setup is raising a Null Pointer Exc. i.e.  in the inversion set phases

To reproduce just try to run an inversion with any rupture set built w Stirling FM e.g. http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/FileDetail/RmlsZTo4OTIuMGtHWmpo

**Comment by voj** [comment]
fix merged into upstream
