### ISSUE TITLE
Feature: configure Deformation Model for Rupture sets

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#169]
SRM want to specify deformation models  in order to apply different deformation models to rupture sets

Examples:
- apply uniform (e.g 10mm) slip rate to entire model
- apply from table of values , one per fault section
- validate whether slip rate is important input to rupture generation in Coulomb builder.

**Comment by voj** [comment]
we agreed to only do a uniform slip rate for now
