### ISSUE TITLE
Feature: Add MEAN support to new NZ Generalised Scaling Relation

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#189]
As cValue internals are not available, we need to allow a MEAN option. Kirans code to replace existing function below.

**Done When**

 - [x] add new MEAN option in the ScalingRelation class (and make it the default)
 - [x] Update getC4log10A2Mw function with new MEAN values
 - [ ] Add some more test coverage for MEAN (Optional, can defer if needed)
 - [x] update ENUMs to cover MEAN in addition to LOWER and UPPER

```
private double getC4log10A2Mw() {
			
		//rhat AKA cValue => perhaps, we refactor rhat as cvalue
		Double rhat = Double.NaN;
		if (faultRegime == CRUSTAL || faultRegime == NONE) {
			if (faultType == NONE || epistemicBound == NONE) {
				return;
			} else if (faultType == STRIKE_SLIP && epistemicBound == MEAN) {
				rhat = 4.0;
			} else if (faultType == STRIKE_SLIP && epistemicBound == LOWER) {
				rhat = 3.65;
			} else if (faultType == STRIKE_SLIP && epistemicBound == UPPER) {
				rhat= 4.30;
			} else if (faultType == REVERSE_FAULTING && epistemicBound == MEAN) {
				rhat = 4.1;
			}	else if (faultType == REVERSE_FAULTING && epistemicBound == LOWER) {
				rhat= 3.95;
			} else if (faultType ==  REVERSE_FAULTING && epistemicBound == UPPER) {
				rhat= 4.30;
			} else if (faultType ==  NORMAL_FAULTING && epistemicBound == MEAN) {
				rhat = 4.1;
			} else if (faultType ==  NORMAL_FAULTING && epistemicBound == LOWER) {
				rhat = 3.95;
			} else if (faultType == NORMAL_FAULTING && epistemicBound == UPPER) {
				rhat = 4.30;
			}
		}
		else if (faultRegime == SUBDUCTION_INTERFACE){
			if (epistemicBound == MEAN) {
				rhat = 3.85;
			} else if (epistemicBound == LOWER) {
				rhat = 3.60;
			} else if (epistemicBound == UPPER) {
				rhat= 4.10;
			} else if (epistemicBound == NONE) {
				return Double.NaN;
			}
		}
		return rhat;
	}
```

**Comment by voj** [comment]
@thingbaijam the first `return` statement in that method does not return a value. I'm going to assume it should return `Double.NaN`

**Comment by thingbaijam** [comment]
Yes. My aplogies for overlooking that one. 


> @thingbaijam the first `return` statement hatin that method does not return a value. I'm going to assume it should return `Double.NaN`

**Comment by voj** [comment]
@thingbaijam thank you!

**Comment by thingbaijam** [comment]
Following the report from Mark, rhat for REVERSE and NORMAL faulting needs an update.

                       if (faultType == NONE || epistemicBound == NONE) {
				return;
			} else if (faultType == STRIKE_SLIP && epistemicBound == MEAN) {
				rhat = 4.0;
			} else if (faultType == STRIKE_SLIP && epistemicBound == LOWER) {
				rhat = 3.65;
			} else if (faultType == STRIKE_SLIP && epistemicBound == UPPER) {
				rhat= 4.30;
			} else if (faultType == REVERSE_FAULTING && epistemicBound == MEAN) {
				rhat = **4.13;**
			}	else if (faultType == REVERSE_FAULTING && epistemicBound == LOWER) {
				rhat= 3.95;
			} else if (faultType ==  REVERSE_FAULTING && epistemicBound == UPPER) {
				rhat= 4.30;
			} else if (faultType ==  NORMAL_FAULTING && epistemicBound == MEAN) {
				rhat = **4.13**;
			} else if (faultType ==  NORMAL_FAULTING && epistemicBound == LOWER) {
				rhat = 3.95;
			} else if (faultType == NORMAL_FAULTING && epistemicBound == UPPER) {
				rhat = 4.30;
			}
