### ISSUE TITLE
Set up & run Inversion DEMO

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#21]
we want to modify kevins' example and apply this to NZ data 

**so that** we have run an inversion on Hikurangi

**Comment by chrisbc** [comment]
FYI @thingbaijam I want to do this soon so we can give feedback to Kevin. Maybe we can run it together late tomorrow (NZ time)

**Comment by thingbaijam** [comment]
> FYI @thingbaijam I want to do this soon so we can give feedback to Kevin. Maybe we can run it together late tomorrow (NZ time)

fine with me! @chrisbc
