### ISSUE TITLE
Gradle CI pipeline in Travis

### ISSUE THREAD

**Issue by ornearius** [GNS-Science/nshm-nz-opensha#26]
As SRM Team

We want an automated build pipeline such that commits to **master** (or otherwise agreed) branch will build the deployables, run the tests, and produce reports on code/test quality 

**So that** we can measure and maintain quality on this codebase.

Assumptions

**Done Criteria**:

 - [x] confirm & agree appropriate build chain

This presents an interesting challenge due to the unique structure of the project

**Comment by chrisbc** [comment]
@ornearius you beat me too it (raising the issue that is) - thanks. I've updated the goals - so can you check them please? 

 I'm assuming that we'll do this in the same Travis account/environment that  Chris VH is using for python project(s)?
