### ISSUE TITLE
Validate impact of azimuth angles on rupture building

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#31]
Currently we have examples of ruptures that start out **north->south** then switch direction to **south->north**. 

TODO attach example.

Done when we can answer these questions:

 - [x] are there any constraints on ruptures relating to azimuth in play now? 
     Please add links to any relevant code in this issue
 - [x] if there are, are they working correctly?
 
NB After these code questions are answered we can ask SRM team if this is enough, or whether more/better constraints are needed (new feature).

**Comment by voj** [comment]
https://github.com/opensha/opensha-ucerf3/tree/master/src/org/opensha/sha/earthquake/faultSysSolution/ruptures/doc#notes-on-azimuth-change-calculations

**Comment by voj** [comment]
I found four possible plausibility filters:

In `org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl`

- JumpAzimuthChangeFilter
- TotalAzimuthChangeFilter

and in `scratch.UCERF3.inversion.laughTest`

- AzimuthChangeFilter
- CumulativeAzimuthChangeFilter

**Comment by chrisbc** [comment]
@voj  FYI here's some debugger output from our earlier [StandaloneRuptureGen example](https://github.com/GNS-Science/nshm-nz-opensha/blob/akatarawa_section_filter/src/main/java/scratch/kevin/ucerf3/StandaloneSubSectRupGenMG.java), and this was able to generate ruptures for the full NZ 2010 crustal model with maxDistance = 0.5

NB This may have relevance to #28 also. I'm seeing several different variations and usages of 'distance' in the above example.

These values are setup here: https://github.com/GNS-Science/nshm-nz-opensha/blob/7a938f96df1992b412eb749dd7a8eb53b7aab577/src/main/java/scratch/kevin/ucerf3/StandaloneSubSectRupGenMG.java#L147

```
laughTest	UCERF3PlausibilityConfig  (id=57)	
	allowSingleSectDuringJumps	true	
	applyGarlockPintoMtnFix	true	
	coulombRates	null	
	coulombTester	CoulombRatesTester  (id=60)	
	laughTests	null	
	maxAzimuthChange	60.0	
	maxCmlAzimuthChange	560.0	
	maxCmlJumpDist	Infinity	
	maxCmlRakeChange	180.0	
	maxJumpDist	5.0	
	maxTotAzimuthChange	60.0	
	minNumSectInRup	2	
	parentSectsToIgnore	null	
	ucerf3p2Filter	false	
```

**Comment by chrisbc** [comment]
All questions answered, and we now know we must get them in play. I'll create a new story for this.
