### ISSUE TITLE
Make project build under Windows

### ISSUE THREAD

**Issue by voj** [GNS-Science/nshm-nz-opensha#32]
so there should be no java source with OS-dependant line-endings in any of these:
 - [ ] nshm-nz-opensha
 - [ ] opensha-core 
 - [ ] opensha-commons
 - [ ] opensha-ucerf3

These are the projects our NSHM builds from. 

Bonus points for:
 - [ ] opensha-dev

For the three opensha upstream repos, please fork into this org (GNS-Science) if they're not forked already.

**Comment by chrisbc** [comment]
written off for now, workaround for @voj in place
