### ISSUE TITLE
add a JumpAzimuthChangeFilter to the crustal CFM inversion script

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#33]
As SRM Team 

**we want** to implement plausability filters as per the UCERF3 model. As of today we have no azimuth filters in our demo code.

**So that** :

 - we can increase the max jump distance to a more reasonable value than 0.25 without "blowing up" 
 - our baseline is more closely aligned with UCERF3

**Done when:**

 - [x] unit test(s) show that jumps are allowed according to the UCERF3 plausability specs for allowed azimuth change at fault-section jumps  [TODO: insert link]()
 - [x] we can demonstrate the impact of this filter on our [CFM crustal data set]()

ref:  https://github.com/GNS-Science/nshm-nz-opensha/issues/31#issuecomment-696483503

**Comment by voj** [comment]
The following runs all had the arguments `-maxFaultSections 1200 -skipFaultSections 0 -maxLength 0.5 -inversionMins 1 -syncInterval 5 -runInversion false -faultIdIn 2`

No azimuth filter:
`-maxDistance 0.275` aborted

With jump filter 60 degrees:
`-maxDistance 0.275` 640 total ruptures
`-maxDistance 0.5` 1093 total ruptures

With all three filters (jump 60, total 60, cumulative 580):
`-maxDistance 0.5` 777 total ruptures
`-maxDistance 1` 803 total ruptures
