### ISSUE TITLE
Data sanity checks

### ISSUE THREAD

**Issue by voj** [GNS-Science/nshm-nz-opensha#34]
We want to make sure that the fault data meets the requirements of the software so that we can avoid runtime errors or silent calculation errors.

- [x] parent fault IDs may not be re-used
- [x] subsection IDs may not be re-used ~~(and they may not use parent IDs)~~
- [x] dip must be greater than 0 and not greater than 90

**Comment by thingbaijam** [comment]
Perhaps, 0< dip <= 90.

**Comment by chrisbc** [comment]
> Perhaps, 0< dip <= 90.

I updated the done criteria to reflect this - thanks @thingbaijam

**Comment by voj** [comment]
@chrisbc should we https://github.com/GNS-Science/opensha-commons/issues/1 now that we have this issue?
