### ISSUE TITLE
Incorporate OpenSHA refactoring to use new FaultSection interface

### ISSUE THREAD

**Issue by kevinmilner** [GNS-Science/nshm-nz-opensha#4]
I just merged in a massive OpenSHA refactor to remove dependence on the FaultSectionPrefData object. That has been replaced with a new [FaultSection](https://github.com/opensha/opensha-commons/blob/master/src/org/opensha/sha/faultSurface/FaultSection.java) interface. This will allow you to create your own subduction representation, with whatever rupture surface you require (i.e., it no longer necessitates StirlingGriddedSurface). You can now also mix representations within a single FaultSystemRuptureSet. Once you pull the changes to the OpenSHA repositories, there will surely be some errors that need fixing in your code. Let me know if you have any questions. I can explain more when we talk next week, and will hopefully have some ideas on down-dip-subsection support.

**Comment by chrisbc** [comment]
Thanks @kevinmilner - this sounds greats. We have some rudimentary tests that might be impacted by this, it'll be very interesting to explore - cheers.

**Comment by chrisbc** [comment]
@kevinmilner new zoom link 

Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://us02web.zoom.us/meeting/tZcpdO2trj8oHdZdQJ_4dPbDzmkwnJZK9u5c/ics?icsToken=98tyKuGrqjguH9SRsh6FRpwqBojCLO_ziClBgqdnmC7PPHRXUgHSLO9JJbxVKvOJ

Join Zoom Meeting
https://us02web.zoom.us/j/83434504272?pwd=YUhxcHdsZ21nbElERk80dVJUeG5SQT09

Meeting ID: 834 3450 4272
Password: 108313

**Comment by chrisbc** [comment]
Hi @kevinmilner 

I've pushed some exploratory tests that I'd like to look at tomorrow, most especially  [InterfaceFaultSectionTest.java
](https://github.com/GNS-Science/nshm-nz-opensha/blob/master/test/NSHM_NZ/inversion/InterfaceFaultSectionTest.java)

using this freshly minted csv data:  [patch_4_10.csv](https://github.com/GNS-Science/nshm-nz-opensha/blob/master/test/NSHM_NZ/inversion/fixtures/patch_4_10.csv)

Right now we have sets that load this data as FaultSection objects, but I'm unsure what's needed next...

**Comment by chrisbc** [comment]
@kevinmilner with the latest [commit ](https://github.com/GNS-Science/nshm-nz-opensha/commit/9ace6698b80344af4710a1a42cca0356d5e488d9) we have the  RuptureGenerator test working with some minimal plausability config (no azimuth or coulomb filtering) . We'll pause now  until we have your mods to support subduction tile layouts.
