### ISSUE TITLE
Split RuptureBuilder script(s) from Inversion script

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#42]
We want to run Inversions from previously built ruptures sets, rather than building these each and every time an inversion is run.

NB this is probably already in UCERF3 code, so let's use that if we can for the inversion stage.

**Done criteria**

 - [x] decide whether to use Kevins **scratch.UCERF3.inversion.CommandLineInversionRunner** in opensha-ucerf3 or not
 - [x] provide a py4j gateway wrapper for python clients

**Comment by chrisbc** [comment]
@voj I'll write a python script that uses the gateway for inversions and fits into the other cluster automation stuff

**Comment by voj** [comment]
We decided against using `scratch.UCERF3.inversion.CommandLineInversionRunner` as this would require a refactor of that class.

**Comment by chrisbc** [comment]
@voj I'll wait on the pull request for the py4j gateway implementation.

**Comment by chrisbc** [comment]
now we have py4j too :)
