### ISSUE TITLE
Validate UCERF3 parity for RuptureSet generation

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#48]
A SRM Team

We want to ensure we can reproduce rupture sets for UCERF3 pre and post recent changes in upstream.

using https://github.com/GNS-Science/opensha-ucerf3/blob/master/src/org/opensha/sha/earthquake/faultSysSolution/ruptures/ClusterRuptureBuilder.java `main()` method
 
so that we have a solid baseline for future NZ variations

**Notes:**

 - save a copy of the output rupset zip file for future reference. 
 - capture basic stats eg number of subsections and number of rupture set generated for future reference
 - pls capture git refs for the code used for this testing.

**Comment by chrisbc** [comment]
(from Slack)

> I expect to see the StandaloneSubSectRupGenMG.java with the UCERF3 default config produce 326078 ruptures, but now it only produces 156960 !??! As per this commit https://github.com/GNS-Science/nshm-nz-opensha/pull/50/commits/20f200b66542a5fa0d4077814c050f987b12d71a 

When you've managed to get a build based on our PRE position to the UCERF3 validations can you also try this out and see if you can get the 326078 ruptures?

**Comment by voj** [comment]
We have identified the changes in the opensha-commons branch `chrisbc_aveDip_is_zero` as the cause of the different rupture count.

# pre latest pull from upstream:

- nshm-nz-opensha: master (1fa959b)
- opensha-commons: 33e9942
- opensha-core: 2bfd0b0
- opensha-ucerf3: db8a593

```
539 Parent Fault Sections
2829 Sub Sections
Created 156960 ruptures
```
[rupSet-prePull.zip](https://github.com/GNS-Science/nshm-nz-opensha/files/5338093/rupSet-prePull.zip)
[ruptures-prePull.zip](https://github.com/GNS-Science/nshm-nz-opensha/files/5338094/ruptures-prePull.zip)

# post latest pull from upstream

- nshm-nz-opensha: 75c00f7
- opensha-commons: 0ff65ea
- opensha-core: eaef275
- opensha-ucerf3: aee5857

```
539 Parent Fault Sections
2829 Sub Sections
Created 156960 ruptures
```
[rupSet.zip](https://github.com/GNS-Science/nshm-nz-opensha/files/5338123/rupSet.zip)
[ruptures.zip](https://github.com/GNS-Science/nshm-nz-opensha/files/5338126/ruptures.zip)

**Comment by chrisbc** [comment]
And @voj you reproduced the UCERF3 rupture sets as Kevin useng /ClusterRuptureBuilder.java main() method PRE == POST. 

So we have confidence that no major changes were introduced :)
