### ISSUE TITLE
Setup travis-ci build on GNS forks of opensha-*

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#49]
For 

 - [ ] https://github.com/GNS-Science/opensha-commons
 - [ ] https://github.com/GNS-Science/opensha-ucerf3

NB we expect that some slow tests may stop this working, and that we'll have to refactor the test configs somewhat. 
Let's keep @kevinmilner posted on this one.

**Comment by ornearius** [comment]
This is now running although there is one test failure in the ucerf3 library. Maybe @kevinmilner would be able to shed some light on this.
If we want to push this upstream then the salient points are that it is setup to build on Java 8 and will pull in the dependent repos where required. There is some clean up stuff in there that is recommended for Gradle builds.
