### ISSUE TITLE
Kaikoura Filter

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#60]
As SRM Team 

**we want** a plausability filter to constrain outputs to those matching faults involved int the Kaikoura 2016 quake

**so that** we can see if that rupture is generated using the NSHM rupture builder/config

**Comment by thingbaijam** [comment]
This data file: finite_fault_mappings.xml looks relevant. However, I could not locate how this is generated. Besides the Kaikoura event, we do have rupture models for some more events in New Zealand.

**Comment by chrisbc** [comment]
@thingbaijam  FYI @voj is building a generalised **havingParticipatingFaultSections** (or somesuchname) plawsfilter (sic). 

This we'll use for **Kaikoura2016** and for any other ruptures we want to investigate. 

We'll be able to set these up very easily from the new rupture diagnostics report that Oakley just extended.

And they can be used either in exploratory hacking, or as integration tests (see #58 )

**Comment by chrisbc** [comment]
some info re Kaik2016:

> Hi all, 

Russ and I have just gone through the CFM faults that ruptured in the 2016 Kaikoura Earthquake:

TheHumps - all
Leader - all
StoneJug – all
Hundalee – partial, NE portion
Papatea – all
Jordan – partial, N portion
Kekerengu1 - all
Needles – almost all, S portion
Fidget – partial, small part of Central

Also very very minor ruptures on:
HopeConwayOS
LondonHill

Cheers,
Nicola

Nicola Litchfield
Earthquake Geologist I Ph +644 570 4891 I Mob +6421 101 3946 

From: Russ van Dissen <R.VanDissen@gns.cri.nz> 
Sent: Friday, 2 October 2020 16:37
To: Matt Gerstenberger <M.Gerstenberger@gns.cri.nz>
Cc: Chris Chamberlain <c.chamberlain@gns.cri.nz>; Nicola Litchfield <N.Litchfield@gns.cri.nz>
Subject: RE: Kaikoura NSHM sources

Matt and Chris,

The current CFM has the Kaikoura Seismic Hazard Model sources in it so will certainly have sources in it that ruptured in 2016. But I will need to double check the exact names of those sources and get back to you. In addition, will probably need to make a table that lists each of the fault zones in the CFM that ruptured in 2016 and whether that fault zone ruptured in its entirety in 2016 or only a portion of it ruptured (e.g. the full length of the Kekerengu Fault ruptured in 2016, whereas only a portion of the Hundalee Fault ruptured in 2016, same for a number of other faults like the Fidget Fault and Jordan Thrust).

**Comment by chrisbc** [comment]
Section IDs (from DEMO5_SANSTVZ_crustal_opensha.xml)
```
TheHumps,400
Leader,178
StoneJug,387
Hundalee,136, partial, NE portion
Papatea,310
Jordan,149,partial, N portion
Kekerengu1,162
Needles,245, – almost all, S portion CBC: check Needles 1 and Needles 2
Fidget,95, – partial, small part of Central

Also very very minor ruptures on:
HopeConwayOS,132
LondonHill,189
```

**Comment by chrisbc** [comment]
was closed with https://github.com/GNS-Science/nshm-nz-opensha/pull/66
