### ISSUE TITLE
Implement coarsening strategy when building crustal ruptures

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#68]
As SRM Team,

**we want** to restrict our number of ~single spine~ crustal ruptures

**so that** we won't end up with too many total ruptures

**Done when**
 - [x] a pseudo-code version for this strategy is agreed with our SRM science team
 - [x] the strategy can still produce the same rupture that the UCERF3 strategy does (i.e. with nil coarsening)
 - [x] the rate of coarsening is configurable (the 'epsilon' value)
 - [x] we show that the new strategy will produces fewer ruptures than current UCERF3 strategy

See excerpt from [this slack thread](https://nshmrevisionproject.slack.com/archives/C013TEKGFMM/p1597259847084500) with Bruce Shaw

> The single spine rupture set is going to be similar to the UCERF3 approach, except we are going to be coarser as the events get longer, as we want to restrict our number of single spine ruptures N_1 to be not so large so that when we combine them with compatible second spines into composite N_2 type ruptures we won't end up with too many total ruptures N_1+N_2=N which isn't too big (i.e. we can do the inversion on it).  We will want to do some capability studies to see how big N can be (ucerf3 had 250,000, but that was some years ago; for the sake of discussion I'll imagine N=1,000,000 is a doable size, but if we can handle bigger we may want to go bigger).  The single spine set is built out similarly to how Kevin built out ucerf3, except as L gets bigger rather than adding 1 more subsection we will add dL=epsilon*L. where epsilon is small.  One does this in both directions from a seed subsection (left down the fault for one set, right down the fault for the other.  finish sets.  move down the fault to the next subsection and repeat).  (This describes the upper plate fault process; in NZ the rupture set for the plate interface is currently differently constructed;  this is fine, however the set is constructed does not impact the double spine set discussion below).

**Comment by voj** [comment]
How ClusterPermutationStrategies are used in opensha:

`sections`: a list of the sections of the maximum extent of a potential rupture.
for each section `startSection` in `sections`: 
ask a ClusterPermutationStrategy for all permutations of a rupture along `sections`:


how UCERF3ClusterPermuationStrategy works:

- first permutation is `startSection`
- travel down `sections` starting at `startSection` to build permutations:
    - each permutation is the previous permutation and the next adjacent section.
- travel up `sections` starting at `startSection` and build permutations in that direction	
    - reset the first `previous permutation` to `startSection`
each permutation is the previous permutation and the next adjacent section.
		
		
Example 1: 

`sections` is [1, 2, 3, 4]
`startSection` is 1
UCERF3ClusterPermuationStrategy returns
[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]

Example 2:

`sections` is [1, 2, 3, 4]
`startSection` is 2
UCERF3ClusterPermuationStrategy returns
[2]
[2, 1]
[2, 3]
[2, 3, 4]

		
how CoarseUCERF3ClusterPermutationStrategy works:

    first permutation is `startSection`
    travel down `sections` starting at `startSection` to build permutations:
		each permutation is the previous permutation and the *next n adjacent sections based on a custom function*.
	travel up `sections` starting at `startSection` and build permutations in that direction	
	    reset the first `previous permutation` to `startSection`
		each permutation is the previous permutation and the *next n adjacent sections based on a custom function*.

**Comment by chrisbc** [comment]
@voj FYI earlier there was some confusion around the meaning of single spine vs double (or multi) spine ruptures as described by Bruce Shaw.

@mcg-gns has since clarified that the **single-spine rupture** is the classic UCERF3 crustal rupture, involving N fault sections and any connections (jumps) between them. In UCERF3 a rupture, at connection points can only 'grow' in one direction along the secondary fault. Viewed from above, this looks like a single spine, especially when the faults have a similar strike (direction).

A **double-spine rupture** is akin to the UCERF(>3) **splay** rupture, where the ruptures can grow in both directions along the secondary fault.

**Comment by chrisbc** [comment]
**NOTA BENE** this solution was discarded and replaced by #76 (see PR https://github.com/GNS-Science/nshm-nz-opensha/pull/78 )  because: 
 - it wasn't actually working as we'd thought  (after discussion with @kevinmilner )
 - in hindsight, the thinning approach was simpler to understand & implement, for very little performance penalty.
