### ISSUE TITLE
Apply background/distributed/gridded seismicity to inversions

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#77]
As SRM team,

**we want** to apply an NZ model of background (off-fault) seismicity 

**so this** information can be incorporated in rate models.

 - [x] where/how is this data applied in ucerf3 (we believe the term "gridded seismicity" is used)
 - [x] what data format is required (csep or similar?)

**Comment by chrisbc** [comment]
Hi @mcg-gns have I got the terms and the intent clear enough here?

**Comment by mcg-gns** [comment]
> Hi @mcg-gns have I got the terms and the intent clear enough here?

We will also need to implement uniform rate models which is a special case of gridded models in OpenSHA. The models probably aren't in CSEP format, that was just an optimistic hope. :)

We need to know if the format and model is any different in the spatial PDF (in the inversion constraints) than for what we will need for the hazard calcs.

**Comment by chrisbc** [comment]
Hi @mcg I got this is from @thingbaijam. I'm beleive  'smoothed seismicity' is a synonym for 'distributed seismicity', but we'll take a look at the code to try to confirm this.
 
> @chrisbc About the input file format for smoothed seismicity models:
> 
> I locate these files at scratch.UCERF3.data.seismicityGrids.  These are *.txt (ascii) files with entries made in three columns (without heading) which can be identified as "latitude', 'longitude' and 'annual rate of seismic activity'.
